moneySettings:
  maxBalance: 999999999
  startingBalance: 5000
  minimumPay: 50

mysql:
  host: "localhost"
  port: 3306
  database: "Minecraft"
  username: "username"
  password: "very secret"


sound:
  soundEnabled: true
  successSound: "BLOCK_NOTE_BLOCK_PLING"
  denySound: "BLOCK_NOTE_BLOCK_BASS"
  pitch: 0.0
  volume: 1.0






messages:
  payPlayer: "You have paid %player% %amount%"
  withdraw: "You have withdrew %amount%"



